import Head from "next/head";
import { useState, useEffect } from "react";
import { useRouter } from "next/router";
import { ethers } from "ethers";
import Navbar from "../../components/nav";
import { FairHub } from "../../components/abis";
import {
  Flex,
  CardSearch,
  NftCardInt,
  NftCard,
  NftImg,
} from "../../components/styles/div";
import { RffId, RffWn, RffEd } from "../../components/styles/typography";
import { Button } from "../../components/styles/button";

function Heading() {
  return (
    <>
      <Head>
        <title>Raffle | Quantum Fair</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
    </>
  );
}

function Search() {
  const [exist, setExist] = useState(false);
  const [image, setImage] = useState(false);
  const { query } = useRouter();

  async function Raffle() {
    try {
      const id = query.id;
      const FairContract = "";
      const ethereum = (window as any).ethereum;
      const accounts = await ethereum.request({
        method: "eth_requestAccounts",
      });
      const provider = new ethers.providers.Web3Provider(ethereum);
      const walletAddress = accounts[0];
      const signer = provider.getSigner(walletAddress);
      const FairProxy = new ethers.Contract(FairContract, FairHub, signer);
      const search = await FairProxy.ids(id);
    } catch (err) {
      console.error(err);
    }
  }

  useEffect(() => {
    Raffle();
  });

  return (
    <>
      <Heading />
      <Navbar />
      <Flex>
        {" "}
        {exist ? (
          <CardSearch>
            {image ? (
              <NftCard>
                <NftImg />
              </NftCard>
            ) : (
              <NftCardInt>
                <NftImg />
              </NftCardInt>
            )}
            <RffId>Raffle #{query.id}</RffId>
            <RffWn>Winners: </RffWn>
            <RffId>End Time: </RffId>
          </CardSearch>
        ) : (
          <CardSearch>
            {image ? (
              <NftCard>
                <NftImg />
              </NftCard>
            ) : (
              <NftCardInt>
                <NftImg src="/images/question.png" />
              </NftCardInt>
            )}
            <RffId>Raffle #{query.id}</RffId>
            <RffWn>Winners: </RffWn>
            <RffEd>End Time: </RffEd>
            <Button
              style={{
                minWidth: "16rem",
                transform: "translate(160px, -40px)",
              }}
            >
              Join to Raffle
            </Button>
          </CardSearch>
        )}
      </Flex>
    </>
  );
}

export default Search;
