import Head from "next/head";
import { useRouter } from "next/router";
import Navbar from "../../components/nav";
import { CardSearch } from "../../components/styles/div";
import { Typography } from "../../components/styles/typography";

function Heading() {
  return (
    <>
      <Head>
        <title>Raffle Board | Quantum Fair</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
    </>
  );
}

function Search() {
  const { query } = useRouter();
  return (
    <>
      <Heading />
      <Navbar />
      <CardSearch>
        <Typography>{query.id}</Typography>
      </CardSearch>
    </>
  );
}

export default Search;
