import Head from "next/head"
import Navbar from "../../components/nav"

function Heading() {
  return (
    <>
      <Head>
        <title>Raffle Board | Quantum Fair</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
    </>
  )
}

function Search({url: any}) {

 return (
   <>
    <Heading />
    <Navbar />
    <h1>{url.query.id}</h1>
   </>
 )
}

export default Search
