import React, { useState } from "react";
import Head from "next/head";
import Link from "next/link";
import { Button, Flex, Input, Stack, Text } from "@chakra-ui/react";

function Heading() {
  return (
    <>
      <Head>
        <title>Raffle Board | Quantum Fair</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
    </>
  );
}

function RaffleBoard() {
  const [raffleId, setraffleId] = useState("");

  return (
    <>
      <Heading />
      <Flex>
        <Text>Raffle Board</Text>
        <Text>Choose the raffle you want to run.</Text>
        <Stack>
          <Input
            onChange={(e) => {
              setraffleId(e.currentTarget.value);
            }}
          />
          <Link
            style={{ textDecoration: "none" }}
            href={`/raffle?id=${raffleId}`}
          >
            <Button>Search</Button>
          </Link>
        </Stack>
      </Flex>
    </>
  );
}

export default RaffleBoard;
