import Head from "next/head";
import Navbar from "../../components/nav";
import styled from 'styled-components'
import CreateRaffle from "../../components/create"

function Heading() {
  return (
    <>
      <Head>
        <title>Create Raffle | Quantum Fair</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/QF-Media kit-ref.png" />
      </Head>
    </>
  )
}

function Create() {
    return (
  <>
    <Heading/>
    <Navbar /> 
    <CreateRaffle />  
  </>
 )
}

export default Create
