import Head from "next/head";
import Navbar from "../components/nav";
function Heading() {
  return (
    <>
      <Head>
        <title>Home | Quantum Fair</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
    </>
  )
}

export default function App() {
  return (
  <>
  <Heading/>
  <Navbar />  
  </>  
  );
}
