import React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import { ethers } from "ethers";
import axios from "axios";
import Navbar from "../../components/nav";
import { FairHub, Raffle, MultiFaucetNFT } from "../../components/abis";
import {
  LabelName,
  LabelStart,
  LabelEnd,
  LabelWinners,
  LabelDesc,
  LabelRff,
  LabelNft,
  LabelID,
  LabelVF,
  LabelVR,
} from "../../components/styles/label";
import { Input, InputOpen, InputDesc } from "../../components/styles/input";
import { Button } from "../../components/styles/button";
import { Flex } from "../../components/styles/div";
import { Typography } from "../../components/styles/typography";

function Heading() {
  return (
    <>
      <Head>
        <title>Create Raffle | Quantum Fair</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
    </>
  );
}

interface CreateData {
  status: number;
  message: string;
  result: {
    0: {
      contractAddress: string;
    };
  };
}
const router=useRouter
function YourRaffleBoard() {
  const vaultFactory = "";
  const vaultRouter = "";
  const [screen, setScreen] = React.useState(false);
  const [canyed, setCanyed] = React.useState(false);
  // const [copied, setCopied] = React.useState(false);
  const [output, setOutput] = React.useState(false);
  const [name, setName] = React.useState("");
  const [start, setStart] = React.useState("");
  const [end, setEnd] = React.useState("");
  const [winners, setWinners] = React.useState("");
  const [description, setDescription] = React.useState("");
  const [nftContract, setnftContract] = React.useState(""); // 0xf5de760f2e916647fd766B4AD9E85ff943cE3A2b
  const [id, setId] = React.useState(""); // 3667556
  const [hub, setHub] = React.useState(""); // 0x38113c10459349fc6e3e65e2c82428781110d5b5

  async function create() {
    try {
      const FairContract = "0x7E0755a50E1C3b2BB8AbECE23F139Be25B8D5348";
      const ethereum = (window as any).ethereum;
      const accounts = await ethereum.request({
        method: "eth_requestAccounts",
      });
      const provider = new ethers.providers.Web3Provider(ethereum);
      const walletAddress = accounts[0];
      const signer = provider.getSigner(walletAddress);
      const FairProxy = new ethers.Contract(FairContract, FairHub, signer);
      const createRaffle = await FairProxy.createRaffle(start, end, winners, {
        hash: "0xf7baab1baf661869e72d3f70214e394102486912b6ed3872d9bb9d7e36e286c3",
        hash_function: 18,
        size: 32,
      });
      await createRaffle.wait();
      const receipt = await provider.getTransactionReceipt(createRaffle.hash);
      if (receipt.status == 1) {
        const bucle = setInterval(async () => {
          await axios
            .post<CreateData>(
              `https://api-goerli.etherscan.io/api?module=account&action=txlistinternal&txhash=${createRaffle.hash}&apikey=GBCBJB46CJB6NMCGMR3X5KENZR3P84RUZH`
            )
            .then((getContract) => {
              if (getContract.data.status == 1) {
                setHub(getContract.data.result[0].contractAddress);
                setCanyed(true);
                setScreen(true);
                clearInterval(bucle);
              }
              return getContract;
            });
        }, 3000);
      }
    } catch (err) {
      console.error(err);
    }
  }

  async function open() {
    try {
      const FaucetContract = nftContract;
      const ethereum = (window as any).ethereum;
      const accounts = await ethereum.request({
        method: "eth_requestAccounts",
      });
      const provider = new ethers.providers.Web3Provider(ethereum);
      const walletAddress = accounts[0];
      const signer = provider.getSigner(walletAddress);
      const MultiFaucet = new ethers.Contract(
        FaucetContract,
        MultiFaucetNFT,
        signer
      );
      const RaffleProxy = new ethers.Contract(hub, Raffle, signer);
      const approve = await MultiFaucet.approve(hub, id);
      const approving = await approve.wait();
      if (approving.status == 1) {
        const opener = await RaffleProxy.open(
          vaultFactory,
          vaultRouter,
          [nftContract],
          [id]
        );
        const opening = await opener.wait();
        if (opening.status == 1) {
          setOutput(true);
        }
      }
    } catch (err) {
      console.error(err);
    }
  }

  return (
    <>
      <Heading />
      <Navbar />
        <div
          className="flex flex-col justify-center content-center	items-center	bg-white w-full min-w-fit px-6"
        >
            <div className="flex flex-col justify-center mt-16 md:w-[1108px] w-80">
                <span className="md:text-[56px] text-[36px] font-bold text-primary-purple text-center">Your raffles board</span>
                <span className="text-base font-normal text-primary-purple mt-2 text-center">All the apps you need to pick random winners from everywhere!</span>
            </div>

            <div className="flex flex-col relative md:mt-[98px] mt-12  md:w-[1108px] w-80">
                <span className="md:text-5xl text-2xl font-bold text-primary-purple md:text-start text-center">My created raffles</span>

                <div className="md:h-[360px] h-[458px] w-full rounded-[20px] md:mt-10 mt-6 border bg-white drop-shadow-[0px 0px 12px 5px rgba(0, 0, 0, 0.12)]">
                    <img className="object-fill md:h-[172px] h-60 w-full rounded-t-[20px]" src="https://github.com/AbelinCoin/Blog-Des-orden-files/blob/main/image%2063.png?raw=true" alt="" />
                    
                    <div className="md:block hidden absolute inset-y-48 left-12 justify-center content-center ">
                        <img className="w-[180px] h-[180px] rounded-lg" src="https://github.com/AbelinCoin/Blog-Des-orden-files/blob/main/image%2064.png?raw=true" alt="" />
                    </div>

                    <div className="md:w-full  md:p-0 p-4 md:pr-6">
                        <div className="md:mt-6 md:w-full md:justify-center flex flex-col">
                            <div className="flex justify-between">
                                <span className="md:ml-[251px] md:text-[36px] text-[24px] font-bold text-black-soft">TheRaffleName</span> 
                                <div className="flex justify-end bg-light-green rounded-full md:w-6 w-4 md:h-6 h-4" ></div>
                            </div>
                            <span className=" md:ml-[251px] md:text-[22px] text-[12px] md:font-medium font-bold text-grey-soft">The raffle description, telling good news</span>
                        </div>

                        <div className="flex md:flex-row flex-col justify-between">
                            <div className="md:ml-12 md:mt-7 mt-4 flex md:flex-row flex-col flex-wrap md:gap-9">
                                <span className="md:text-base font-medium text-grey-soft">Participants:<span className="md:text-base font-bold text-grey-soft">1215</span></span> 
                                <span className="md:text-base font-medium text-grey-soft">Last join:<span className="md:text-base font-bold text-grey-soft">12 min ago</span></span>
                                <span className="md:text-base font-medium text-grey-soft">Time remaining:<span className="md:text-base font-bold text-grey-soft">22 days</span></span>
                            </div>
                            <div className="md:mt-4 mt-4 flex flex-row gap-4">
                                <button className="md:h-10 h-8 md:w-[160px] w-full rounded-lg border-[2px] border-light-purple bg-white font-bold text-base text-light-purple">View more</button>
                                <button className="md:h-10 h-8 md:w-[160px] w-full rounded-lg border bg-light-purple font-bold text-base text-white">Close raffle</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div className="flex flex-row justify-between content-center md:mt-[72px] mt-8 md:w-[1108px] w-80 md:h-[72px] h-[66px] py-2 px-4 bg-purple-grey rounded-2xl">
                <div className="flex content-center justify-start flex-wrap gap-2 md:ml-4">
                    <span className="md:text-2xl text-base font-bold text-primary-purple">Instagram 20K followers</span>
                    <span className="md:block hidden md:text-2xl font-bold text-primary-purple">-</span>
                    <span className="md:text-2xl text-xs font-bold text-primary-purple">RAFFLE ID #3667</span>
                </div>

                <div className="flex flex-row items-center justify-center gap-[18px] h-full">
                    <div className="bg-light-green rounded-full md:w-6 w-4 md:h-6 h-4"></div>
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2.5" stroke="currentColor" className="w-6 h-6 stroke-primary-purple">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M4.5 15.75l7.5-7.5 7.5 7.5" />
                    </svg>
                </div>
            </div>

            <div className="flex flex-row justify-between content-center md:mt-5 mt-4 md:w-[1108px] w-80 md:h-[72px] h-[66px] py-2 px-4 bg-purple-grey rounded-2xl">
                <div className="flex content-center justify-start flex-wrap gap-2 md:ml-4">
                    <span className="md:text-2xl text-base font-bold text-primary-purple">Instagram 20K followers</span>
                    <span className="md:block hidden md:text-2xl font-bold text-primary-purple">-</span>
                    <span className="md:text-2xl text-xs font-bold text-primary-purple">RAFFLE ID #3667</span>
                </div>

                <div className="flex flex-row items-center justify-center gap-[18px] h-full">
                    <div className="bg-light-yellow rounded-full md:w-6 w-4 md:h-6 h-4"></div>
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2.5" stroke="currentColor" className="w-6 h-6 stroke-primary-purple">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M4.5 15.75l7.5-7.5 7.5 7.5" />
                    </svg>
                </div>
            </div>

            <div className="flex md:w-[1108px] w-80 justify-end md:mt-16 mt-14 mb-16"> 
                <button
                className="md:h-[56px] h-[52px] md:w-[290px] w-[212px] rounded-2xl border bg-secondary-purple font-bold md:text-2xl text-base text-white">
                Create New Raffle
                </button>
            </div>

            <div className="h-[1.5px] md:w-[1108px] w-80 bg-primary-purple"></div>

            <div className="flex md:justify-between justify-center flex-wrap gap-4 md:w-[1108px] w-80 md:mt-20 mt-16">
                <span className="md:text-5xl text-2xl font-bold text-primary-purple md:text-start text-center">Participating raffles</span>
                <div className="flex flex-col md:text-end text-center">
                    <span className="md:text-base font-bold text-primary-purple">Address:<span className="md:text-base font-bold text-light-purple">0x321...4vb2</span></span>
                    <span className="md:text-base font-bold text-primary-purple">Total amount:<span className="md:text-base font-bold text-light-purple">21.45 USDC</span></span>
                </div>
            </div>

            <div className="flex flex-row justify-between content-center md:mt-12 mt-8 md:w-[1108px] w-80 md:h-[72px] h-[66px] py-2 px-4 bg-purple-grey rounded-2xl">
                <div className="flex content-center justify-start flex-wrap gap-2 md:ml-4">
                    <span className="md:text-2xl text-base font-bold text-primary-purple">Instagram 20K followers</span>
                    <span className="md:block hidden md:text-2xl font-bold text-primary-purple">-</span>
                    <span className="md:text-2xl text-xs font-bold text-primary-purple">RAFFLE ID #3667</span>
                </div>

                <div className="flex flex-row items-center justify-center gap-[18px] h-full">
                    <div className="bg-light-green rounded-full md:w-6 w-4 md:h-6 h-4"></div>
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2.5" stroke="currentColor" className="w-6 h-6 stroke-primary-purple">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M4.5 15.75l7.5-7.5 7.5 7.5" />
                    </svg>
                </div>
            </div>

            <div className="flex flex-row justify-between content-center md:mt-5 mt-4 md:w-[1108px] w-80 md:h-[72px] h-[66px] py-2 px-4 bg-purple-grey rounded-2xl">
                <div className="flex content-center justify-start flex-wrap gap-2 md:ml-4">
                    <span className="md:text-2xl text-base font-bold text-primary-purple">Instagram 20K followers</span>
                    <span className="md:block hidden md:text-2xl font-bold text-primary-purple">-</span>
                    <span className="md:text-2xl text-xs font-bold text-primary-purple">RAFFLE ID #3667</span>
                </div>

                <div className="flex flex-row items-center justify-center gap-[18px] h-full">
                    <div className="bg-light-yellow rounded-full md:w-6 w-4 md:h-6 h-4"></div>
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2.5" stroke="currentColor" className="w-6 h-6 stroke-primary-purple">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M4.5 15.75l7.5-7.5 7.5 7.5" />
                    </svg>
                </div>
            </div>

            <div className="flex flex-row justify-between content-center md:mt-5 mt-4 md:mb-96 mb-36 md:w-[1108px] w-80 md:h-[72px] h-[66px] py-2 px-4 bg-purple-grey rounded-2xl">
                <div className="flex content-center justify-start flex-wrap gap-2 md:ml-4">
                    <span className="md:text-2xl text-base font-bold text-primary-purple">Instagram 20K followers</span>
                    <span className="md:block hidden md:text-2xl font-bold text-primary-purple">-</span>
                    <span className="md:text-2xl text-xs font-bold text-primary-purple">RAFFLE ID #3667</span>
                </div>

                <div className="flex flex-row items-center justify-center gap-[18px] h-full">
                    <div className="bg-light-yellow rounded-full md:w-6 w-4 md:h-6 h-4"></div>
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2.5" stroke="currentColor" className="w-6 h-6 stroke-primary-purple">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M4.5 15.75l7.5-7.5 7.5 7.5" />
                    </svg>
                </div>
            </div>

        </div>
    </>
  );
}
export default YourRaffleBoard;
